// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

// user table
type USER struct {
	Id           uint      `gorm:"column:id;type:int(11) unsigned;primary_key;AUTO_INCREMENT;comment:primary key"`     // primary key
	IpAddress    int       `gorm:"column:ip_address;type:int(11);index:ip_addresskey;default:0;NOT NULL;comment:ip地址"` // ip地址
	Nickname     string    `gorm:"column:nickname;type:varchar(128);uniqueIndex:nicknamekey;NOT NULL;comment:名称"`      // 名称
	Description  string    `gorm:"column:description;type:varchar(256);NOT NULL;comment:描述"`                           // 描述
	CreatorEmail string    `gorm:"column:creator_email;type:varchar(64);NOT NULL;comment:创建人email"`                    // 创建人email
	CreatedAt    time.Time `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP;NOT NULL;comment:创建时间"`    // 创建时间
	DeletedAt    time.Time `gorm:"column:deleted_at;type:datetime;comment:删除时间"`                                       // 删除时间
	Info         string    `gorm:"column:info;type:longtext;NOT NULL;comment:信息"`                                      // 信息
}

func (m *USER) TableName() string {
	return "USER"
}


